# Generated by Django 3.1.6 on 2021-03-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_auto_20210314_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categories',
            field=models.ManyToManyField(blank=True, to='restaurant.Categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
