# Generated by Django 3.1.6 on 2021-05-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0048_auto_20210519_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='est_menu_tacos',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
