# Generated by Django 3.1.6 on 2021-05-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0055_auto_20210526_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='est_assiette_salade',
            new_name='est_assiette',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='est_panini_croq',
            new_name='est_croque',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_pate',
        ),
        migrations.AddField(
            model_name='produit',
            name='est_panini',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_salade_pate',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
