# Generated by Django 3.1.6 on 2021-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0060_auto_20210527_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplement',
            name='sup_mix_viande',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
