# Generated by Django 3.1.6 on 2021-08-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0065_auto_20210608_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_menu_family',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='taille_pizza',
            field=models.CharField(blank=True, choices=[('Moyenne', 'moyenne'), ('Petite', 'petite')], max_length=100, null=True),
        ),
    ]
