# Generated by Django 3.1.6 on 2021-09-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0068_formulairecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='taille_pizza',
            field=models.CharField(blank=True, choices=[('Moyenne', 'moyenne'), ('Petite', 'petite')], default='', max_length=100, null=True),
        ),
    ]
