# Generated by Django 3.0.2 on 2020-09-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('postal_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=45)),
                ('capital', models.FloatField()),
                ('SIRET_number', models.CharField(max_length=14)),
                ('retirement_fund_name', models.CharField(max_length=45)),
                ('retirement_fund_address', models.CharField(max_length=45)),
                ('retirement_fund_city', models.CharField(max_length=45)),
                ('retirement_fund_postal_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('postal_code', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
    ]
