# Generated by Django 3.1.1 on 2020-12-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='restaurants',
            field=models.ManyToManyField(blank=True, to='main.Restaurant'),
        ),
    ]
