# Generated by Django 3.1.1 on 2021-01-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201222_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='company',
        ),
    ]
