# Generated by Django 3.1.1 on 2021-05-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210507_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaisseRetraite',
        ),
        migrations.DeleteModel(
            name='Dirigeant',
        ),
        migrations.DeleteModel(
            name='Societe',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='info_restaurant',
        ),
        migrations.DeleteModel(
            name='Info_Restaurant',
        ),
    ]
