# Generated by Django 3.1.6 on 2021-03-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0017_auto_20210219_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='montant',
            field=models.FloatField(default=0.0),
        ),
    ]
