# Generated by Django 3.1.6 on 2021-03-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0018_client_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='infos_menus',
            field=models.TextField(null=True),
        ),
    ]
