# Generated by Django 3.2.4 on 2021-06-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0065_auto_20210608_1253'),
        ('paiement', '0028_auto_20210608_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='infos_produits',
        ),
        migrations.CreateModel(
            name='Panier_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.produit')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(blank=True, to='paiement.Panier_produit'),
        ),
    ]
