# Generated by Django 3.1.6 on 2021-06-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210520_0959'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantowner',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
        migrations.AddField(
            model_name='restaurantowner',
            name='company_position',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='restaurantowner',
            name='nom',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='restaurantowner',
            name='phone_number',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='restaurantowner',
            name='prénom',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='restaurantowner',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
    ]
