# Generated by Django 3.1.1 on 2020-12-22 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201222_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
    ]
