# Generated by Django 3.1.6 on 2021-03-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_formulairecontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulairecontact',
            name='prestation',
        ),
        migrations.AlterField(
            model_name='formulairecontact',
            name='societe',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MenuChoixProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement', models.FloatField(default=0)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.produit')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='choix_produits',
            field=models.ManyToManyField(blank=True, to='restaurant.MenuChoixProduit'),
        ),
    ]
