# Generated by Django 3.1.6 on 2021-03-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_formulairecontact_prestations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulairecontact',
            old_name='prestations',
            new_name='prestation',
        ),
    ]
