# Generated by Django 3.1.6 on 2021-03-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0022_auto_20210314_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='nom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
