# Generated by Django 3.1.6 on 2021-03-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0026_auto_20210314_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='categories',
            new_name='categories_produits',
        ),
    ]
