# Generated by Django 3.1.6 on 2021-03-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_auto_20210314_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
