# Generated by Django 3.1.6 on 2021-03-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0033_info_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='au_menu',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
