# Generated by Django 3.1.6 on 2021-03-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_produit_au_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accompagnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/images')),
                ('prix', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='au_menu',
            new_name='sur_grill',
        ),
    ]
