# Generated by Django 3.1.6 on 2021-03-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0035_auto_20210324_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='au_menu',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
