# Generated by Django 3.1.6 on 2021-05-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0045_auto_20210519_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='disponibilite',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_menu_burgers',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_menu_sandwich',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_menu_tacos',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='taille_pizza',
        ),
    ]
