# Generated by Django 3.1.6 on 2021-05-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0049_supplement_est_menu_tacos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='est_menu_sandwich',
            new_name='est_menu_crepe_salee',
        ),
        migrations.RenameField(
            model_name='supplement',
            old_name='est_menu_sandwich',
            new_name='est_frite',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='image',
        ),
        migrations.AddField(
            model_name='produit',
            name='commentaire_produit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_enfant',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_paninis_croque',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_sandwichs',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_sandwichs_au_four',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='est_menu_sandwichs_au_four',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='est_menu_sandwichs_crepe_salee',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='est_milshake_crepe',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='est_pizzas',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='est_smoothie',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type_ingredient',
            field=models.CharField(blank=True, choices=[('Pain', 'pain'), ('Viande', 'viande'), ('Sauce', 'sauce'), ('Crudite', 'crudite')], max_length=100, null=True),
        ),
    ]
