# Generated by Django 3.1.6 on 2021-05-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0056_auto_20210526_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='est_menu_paninis_croq',
        ),
        migrations.AddField(
            model_name='produit',
            name='est_dessert',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_croque',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_paninis',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='supplement',
            name='type_supplement',
            field=models.CharField(blank=True, choices=[('Pain', 'pain'), ('Viande', 'viande'), ('Sur_frite', 'sur_frite'), ('Sauce', 'sauce'), ('Crudite', 'crudite'), ('Fromage', 'fromage'), ('Dessert', 'dessert')], max_length=100, null=True),
        ),
    ]
