# Generated by Django 3.1.6 on 2021-05-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0057_auto_20210526_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplement',
            name='type_supplement',
            field=models.CharField(blank=True, choices=[('Pain', 'pain'), ('Viande', 'viande'), ('Sur_frite', 'sur_frite'), ('Sauce', 'sauce'), ('Crudite', 'crudite'), ('Fromage', 'fromage'), ('Dessert', 'dessert'), ('TaillePizza', 'TaillePizza')], max_length=100, null=True),
        ),
    ]
