# Generated by Django 3.1.6 on 2021-05-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0059_auto_20210527_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='est_milkshake_smoothie',
        ),
        migrations.AddField(
            model_name='produit',
            name='est_milkshake',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_smoothie',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
