# Generated by Django 3.1.6 on 2021-09-07 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0065_auto_20210608_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=26)),
                ('prenom', models.CharField(max_length=26)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('situation', models.CharField(max_length=26)),
                ('echeance', models.CharField(max_length=26)),
                ('ville', models.CharField(max_length=26)),
                ('apport', models.CharField(max_length=26)),
                ('message', models.TextField()),
                ('date_message', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
