# Generated by Django 3.1.6 on 2021-04-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0019_panier_infos_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier_produit',
            name='accompagement',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
