# Generated by Django 3.1.6 on 2021-04-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0021_auto_20210402_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panier_produit',
            old_name='accompagement',
            new_name='accompagnement',
        ),
    ]
