# Generated by Django 3.1.6 on 2021-04-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0023_commande_livraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_public_key', models.TextField(blank=True, null=True)),
                ('google_maps_key', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
