# Generated by Django 3.1.6 on 2021-05-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0025_auto_20210519_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='infos_panier',
            field=models.TextField(null=True),
        ),
    ]
