# Generated by Django 3.0 on 2021-06-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0062_auto_20210528_1044'),
        ('paiement', '0026_panier_infos_panier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='infos_panier',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='infos_produits',
        ),
        migrations.CreateModel(
            name='Panier_produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.Produit')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(blank=True, to='paiement.Panier_produit'),
        ),
    ]
