# Generated by Django 3.2.4 on 2021-06-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0027_auto_20210604_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panier',
            name='produits',
        ),
        migrations.AddField(
            model_name='panier',
            name='infos_produits',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Panier_produit',
        ),
    ]
