# Generated by Django 3.1.6 on 2021-06-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0031_auto_20210609_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier_produit',
            name='supplements',
            field=models.TextField(null=True),
        ),
    ]
