# Generated by Django 3.1.6 on 2021-06-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0032_panier_produit_supplements'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier_produit',
            name='information',
            field=models.TextField(null=True),
        ),
    ]
