# Generated by Django 3.1.6 on 2021-03-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_auto_20210313_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaireContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=26)),
                ('prenom', models.CharField(max_length=26)),
                ('societe', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('prestation', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
