# Generated by Django 3.1.6 on 2021-03-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_auto_20210314_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='categories',
        ),
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
