# Generated by Django 3.1.6 on 2021-03-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_menuchoixproduit_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='produits',
        ),
    ]
