# Generated by Django 3.1.6 on 2021-03-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0029_auto_20210314_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='prix',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
