# Generated by Django 3.1.6 on 2021-05-19 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0046_auto_20210519_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.categorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='disponibilite',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_burgers',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_sandwich',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_tacos',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='taille_pizza',
            field=models.FloatField(default=1.5),
        ),
    ]
