# Generated by Django 3.2.4 on 2021-06-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0063_supplementviande1_supplementviande2_supplementviande3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplementViande1',
        ),
        migrations.DeleteModel(
            name='SupplementViande2',
        ),
        migrations.DeleteModel(
            name='SupplementViande3',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='est_menu_tacos',
            new_name='est_menu_tacos_viande1',
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_tacos_viande2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_tacos_viande3',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
