# Generated by Django 3.2.4 on 2021-06-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montantHT', models.FloatField(blank=True)),
                ('montantTVA', models.FloatField(blank=True, choices=[(5.5, '5.5'), (10, '10'), (20, '20')])),
                ('fournisseur', models.CharField(blank=True, max_length=15)),
                ('date_achat', models.IntegerField(blank=True, null=True)),
                ('photo_facture', models.ImageField(blank=True, null=True, upload_to='static/images')),
            ],
        ),
    ]
