# Generated by Django 3.1.6 on 2021-02-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20210218_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='categories',
        ),
    ]
