# Generated by Django 3.1.6 on 2021-03-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_auto_20210314_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApparteniAuCategorie',
            new_name='AppartenirAuCategorie',
        ),
    ]
