# Generated by Django 3.1.6 on 2021-03-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_auto_20210322_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilite_restaurant', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
