# Generated by Django 3.1.6 on 2021-03-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0038_produit_prix_supplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accompagnement',
            name='image',
            field=models.ImageField(null=True, upload_to='staticfiles/images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(null=True, upload_to='staticfiles/images'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(null=True, upload_to='staticfiles/images'),
        ),
    ]
