# Generated by Django 3.1.6 on 2021-05-19 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0025_auto_20210519_1343'),
        ('restaurant', '0043_auto_20210406_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='static/images')),
                ('prix', models.FloatField(blank=True, default=0)),
                ('disponibilite', models.BooleanField(default=False, null=True)),
                ('est_menu_sandwich', models.BooleanField(default=False, null=True)),
                ('est_menu_burgers', models.BooleanField(default=False, null=True)),
                ('est_menu_tacos', models.BooleanField(default=False, null=True)),
                ('est_assiettes', models.BooleanField(default=False, null=True)),
                ('est_pizzas_sauce_tomate', models.BooleanField(default=False, null=True)),
                ('est_pizzas_creme_fraiche', models.BooleanField(default=False, null=True)),
                ('est_hors_serie', models.BooleanField(default=False, null=True)),
                ('est_crepes_salees', models.BooleanField(default=False, null=True)),
                ('est_crepes_sucrees', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Accompagnement',
        ),
        migrations.RemoveField(
            model_name='apparteniraucategorie',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='apparteniraucategorie',
            name='menus',
        ),
        migrations.DeleteModel(
            name='FormulaireContact',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='categories_produits',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='choix_produits',
        ),
        migrations.RemoveField(
            model_name='menuchoixproduit',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='menuchoixproduit',
            name='produit',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='accompagnement',
            new_name='est_assiettes',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='au_menu',
            new_name='est_boissons',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='supplement',
            new_name='est_crepes_salees',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='sur_grill',
            new_name='est_crepes_sucrees',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='prix_supplement',
            new_name='taille_pizza',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='description',
        ),
        migrations.AddField(
            model_name='produit',
            name='est_frites',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_hors_serie',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_burgers',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_sandwich',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_menu_tacos',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_pains',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_pizzas_creme_fraiche',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_pizzas_sauce_tomate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='est_viande',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='AppartenirAuCategorie',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuChoixProduit',
        ),
        migrations.AddField(
            model_name='supplement',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.categorie'),
        ),
    ]
