# Generated by Django 3.1.6 on 2021-05-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0044_auto_20210519_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type_ingredient', models.CharField(blank=True, choices=[('Pain', 'pain'), ('Viande', 'viande'), ('Fruit et Légume', 'fruit_legume')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_assiettes',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_boissons',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_crepes_salees',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_crepes_sucrees',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_frites',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_hors_serie',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_pains',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_pizzas_creme_fraiche',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_pizzas_sauce_tomate',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='est_viande',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='est_assiettes',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='est_crepes_salees',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='est_crepes_sucrees',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='est_hors_serie',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='est_menu_tacos',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='est_pizzas_creme_fraiche',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='est_pizzas_sauce_tomate',
        ),
    ]
