# Generated by Django 3.1.6 on 2021-05-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0051_auto_20210524_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.AddField(
            model_name='info_restaurant',
            name='disponibilite_livraison',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
