# Generated by Django 3.2.4 on 2021-06-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_alter_facture_photo_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='photo_facture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
